- src/order-history/OrderHistoryPage.jsx
> fix: error display should not also show empty orders message

- package-lock.json
- package.json
- src/order-history/OrderHistoryPage.jsx
Uses react-responsive (new dependency) to swap table rendering.
On mobile the data is rendered as a series of `div` containing a `dl`.
> feat: add mobile table view

- src/order-history/OrderHistoryPage.jsx
- src/order-history/actions.js
- src/order-history/reducer.js
- src/order-history/saga.js
- src/order-history/service.js
- use line item description instead of product id because product is sometimes null
- we don't expect any errors from our API call so add error logging and push the user to the error page
> fix: add error logging and remove use of unreliable product.id

- src/order-history/OrderHistoryPage.jsx
- src/order-history/OrderHistoryPage.messages.jsx
Order detail table does not have header for 'view order details' column which may affect user experience in terms of a11y.In this PR, header text is added to order table.
> Add header for view order details.

- package-lock.json
- package.json
[REV-2050](https://openedx.atlassian.net/browse/REV-2050). 
Upgrading the below because of security vulnerabilities: 
- frontend-platform 
These were dependencies that had high vulnerabilities and were also updated:
- bl
- elliptic
- selfsigned
- lodash
- dot-prop
- decompress
- http-proxy
- acorn
And these were moderate/low but had lots of instances:
- terser-webpack-plugin
- minimist
- kind-of
> Upgrade packages with security vulnerabilities

- README.rst
Removing references to the PurgeCSS library from the Readme doc
To eliminate confusion in the Readme about a library that is no longer used. The library was intentionally removed in https://github.com/edx/frontend-app-ecommerce/pull/73 because the library is a somewhat dangerous way to cut down on css bloat and for this particular app, it was decided that performance was less important than the risk incurred by using purgecss.
> Update readme to reflect removal of purgecss

- package-lock.json
- package.json
- public/index.html
- src/common/utils.js
- src/common/utils.test.js
- src/index.jsx
- src/index.scss
- src/order-history/OrderHistoryPage.jsx
- src/order-history/saga.js
- src/reducers.js
On the order history page: 
-Update the favicon with the new brand logo
-Update the colors/fonts/styles with the new brand colors/fonts/styles
Followed the upgrade instructions per [update instructions](https://openedx.atlassian.net/wiki/spaces/AC/pages/1996325015/Brand+Upgrade+edx-internal#MFE-Style%2FFont%2FLayout-Upgrade-Process) and [logo/favicon instructions](https://openedx.atlassian.net/wiki/spaces/AC/pages/2047345474/Logo+Flip+Plan+and+Instructions#MFE-Logo-Instructions)
Edx recently updated the colors/fonts/styles so we are updating this page to match.
Normal screen
Favicon (I think the circles one will be replaced with the real logo in production; note that the existing logo was already changed in production)
On hover of the user dropdown
On hover of the courses menu item
This …
> [REV-1611] Update order history page with new edx brand styles

- package-lock.json
- package.json
- src/order-history/__snapshots__/OrderHistoryPage.test.jsx.snap
Update the Paragon library from 7.1.3 to 12.7.1 
So we can use the updated header library component (frontend-component-header-edx) in stage & production
Ticket: https://openedx.atlassian.net/browse/REV-2070
> [REV-2070] Bump paragon library version

- package-lock.json
- package.json
Bump the `prop-types` library to 15.7.2
See https://github.com/algolia/react-instantsearch/pull/3003
This was breaking in the local development environment at runtime in the browser. Not sure why it wasn't breaking in stage and production.
> [REV-2070] Bump prop-types dependency to 15.7.2

- .env
Set the `NODE_ENV='production'` in the `.env` file, similar to what newer mfes (e.g. https://github.com/edx/frontend-app-payment/blob/master/.env#L1) do
We're getting an error in the Stage + Prod environments's Javascript console about ```redux.js:307 You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.```
We think this is due to the fact that the env isn't specified when the app starts (it's set to "null" in the prod environment), which we think is ultimately pulled from the …
> Set NODE_ENV='production' in .env file

- README.rst
Recommend `npm ci` over `npm install` to minimize package_lock changes and match CI and prod builds
> Update README to recommend `npm ci`

- .github/PULL_REQUEST_TEMPLATE.md
Add an expanded PR template that also directs edX engineers to instructions for deploying their changes
> REV-2099: Add an expanded PR template

- openedx.yaml
Also removed two obsolete keys.
This repo should be included in Open edX releases, but the openedx.yaml didn't correctly indicate this.  Now it does.
> build: include this repo in Open edX releases

- Makefile
- package-lock.json
- package.json
- src/order-history/OrderHistoryPage.messages.jsx
[REV-2643](https://openedx.atlassian.net/browse/REV-2643).
Transifex is deprecating its version 2, we need to update to v3 so our scripts don't fail when the change happens on April 7th, 2022.
**This PR:**
- Remove `reactifex` dependency and add our maintained version `@edx/reactifex`
- Update Makefile commands for new v3 transifex API
- Edit one description in the message file to test push translation job
> chore: Update transifex api from v2 to v3

- .github/workflows/node-ci.yml
This PR move the codecov in CI to the latest version in order to keep it consistent with frontend repos being updated to v3
> Update codecov uploader in CI

- .github/workflows/node-ci.yml
[REV-2812](https://2u-internal.atlassian.net/browse/REV-2812).
Reverts openedx/frontend-app-ecommerce#190
`frontend-platform` needs to be updated to version 2.4.0 however there's a dev dependency issue with `frontend-component-footer` + `frontend-platform` in this repo that needs to be fixed first.
Reverting this to unblock the pipeline for other commits.
> Revert "Update codecov uploader in CI"

- package-lock.json
- package.json
[REV-2812](https://2u-internal.atlassian.net/browse/REV-2812).
This is an attempt to unblock the pipeline after this PR https://github.com/openedx/frontend-app-ecommerce/pull/190 was merged/reverted.
**Upgrading:**
- edx/frontend-platform from v1.15.3 to v2.4.0
- edx/frontend-component-footer from v10.2.1 to v11.1.1
_Note_: manually upgrading or running `npm install @edx/frontend-platform@latest`, as well as deleting `package-lock.json` completely was not possible due to dependency tree issues. 
`--legacy-peer-deps` was used in this PR, as it's the preferred workaround/last resort for issues like this.
> fix: Upgrade frontend-component-footer and frontend-platform

- package-lock.json
- package.json
[REV-2812](https://2u-internal.atlassian.net/browse/REV-2812).
After PR https://github.com/openedx/frontend-app-ecommerce/pull/198 was merged, looks like there's another peer dependency issue in the `prop-types` version ([see GoCD error](https://gocd.tools.edx.org/go/tab/build/detail/stage-frontend-app-ecommerce/41/stage_frontend-app-ecommerce_build_frontend/1/stage_frontend-app-ecommerce_build_frontend_job).)
**This PR:** 
- Upgrades `prop-types` from v15.7.2 to v15.8.1
> fix: Upgrade proptypes to v15.8.1

- src/order-history/OrderHistoryPage.jsx
**TL;DR -** Fixes writing direction for the quantity multiplier (x operator) in the order history table.
- When multiplication is written using an attached 'x' character, the number and x are treated as a single LTR word, thus not following the proper direction for RTL languages.
- The fix consists of replacing 'x' character with the '&times;' operator (treated as punctuation)
**Rejected fix candidates:**
- **Add a space before the 'x':** works but the added space causes quantity and 'x' to be on 2 separate lines when in small screen.
- **Use a spaceless character 'RLM' to fix direction only for RTL:** it works but needs to add another condition to apply the fix only for RTL language, which implies more code (+1 import), which is not as clean as replacing only a single character.
- On …
> Fix [RTL]: align order item quantity multiplier with text direction

- README.rst
In [REV-2687](https://2u-internal.atlassian.net/browse/REV-2687), I'm updating get_receipt_page_url to be able to send people to the old ecommerce receipt, or the new one coming in frontend-app-ecommerce. While it's fresh, here's an update to the README file with the configuration info needed to send people to the new receipt. 
The new receipt page won't be ready until after my last day, so I've logged a ticket here and sorted in the backlog to merge this PR when ready:  https://2u-internal.atlassian.net/browse/REV-2842
> fix: add notes for receipt setup

- renovate.json
We are currently experimenting with changing our Renovate configuration.
Mirror Renovate changes to frontend-app-payment to frontend-app-ecommerce.
* Jira: [REV-1551](https://2u-internal.atlassian.net/browse/REV-1551) Configure Renovate in frontend-app-payment and frontend-app-ecom for dependency updates
* Research: [Confluence](https://2u-internal.atlassian.net/wiki/spaces/~931919476/pages/28246096/REV-1551)
Check Renovate is working after merge.
> build: [REV-1551] update renovate.json to match f-a-payment

- src/index.jsx
- src/index.scss
- src/order-history/OrderHistoryPage.jsx
- src/order-history/OrderHistoryPage.test.jsx
- src/order-history/__snapshots__/OrderHistoryPage.test.jsx.snap
- src/order-history/index.js
- src/orders-and-subscriptions/OrdersAndSubscriptionsPage.jsx
- src/orders-and-subscriptions/OrdersAndSubscriptionsPage.test.jsx
- src/orders-and-subscriptions/__snapshots__/OrdersAndSubscriptionsPage.test.jsx.snap
- src/orders-and-subscriptions/_style.scss
- src/orders-and-subscriptions/index.js
- src/subscriptions/SubscriptionScrollView.jsx
- src/subscriptions/SubscriptionUpsell.jsx
- src/subscriptions/Subscriptions.jsx
- src/subscriptions/Subscriptions.test.jsx
- src/subscriptions/__snapshots__/Subscriptions.test.jsx.snap
- src/subscriptions/index.js
Subscription related design changes
Relevant Jira Issues [PON-106](https://2u-internal.atlassian.net/browse/PON-106), [PON-80](https://2u-internal.atlassian.net/browse/PON-80)
> PON-106&80: Subscription related design changes

- src/orders-and-subscriptions/OrdersAndSubscriptionsPage.jsx
- src/orders-and-subscriptions/OrdersAndSubscriptionsPage.messages.js
- src/subscriptions/ManageSubscriptionsPage.jsx
- src/subscriptions/ManageSubscriptionsPage.messages.js
Fix various unmarked translations
> fix: fix unmarked translations

- package-lock.json
- package.json
Update the frontend-platform version to fix issues with react-router v6 for instances where the PUBLIC_PATH is used for MFEs instead of the separate domains for each MFE.
The minimum satisfying version of the frontend-platform is v5.5.1 https://github.com/openedx/frontend-platform/releases/tag/v5.5.1
The same fix is already applied to the master:
https://github.com/openedx/frontend-app-ecommerce/pull/340/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
I tested on domain-based (devstack) and PUBLIC_PATH-based (our Dev) instances.
> fix: update frontend-platform version

- .github/workflows/node-ci.yml
This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/frontend-app-ecommerce/issues/392
> build: Switch to ubuntu-latest for builds
