openedx/frontend-app-ecommerce

src/index.scss, src/order-history/OrderHistoryPage.jsx, src/order-history/OrderHistoryPage.messages.jsx, src/order-history/_style.scss, src/order-history/service.js
=> feat: update api service to transform data and render order history table

src/environment.js, src/order-history/OrderHistoryPage.jsx, src/order-history/actions.js, src/order-history/mockOrdersResponse.json, src/order-history/reducer.js, src/order-history/saga.js, src/order-history/service.js, webpack/webpack.dev.config.js, webpack/webpack.prod.config.js
- Pagination is not included. This will currently fetch the first page of 100 results.
=> feat: add api endpoint

src/components/App.jsx, src/index.jsx, src/index.scss, src/payments/PaymentsPage.jsx, src/payments/PaymentsPage.messages.jsx, src/payments/_style.scss, src/payments/actions.js, src/payments/index.js, src/payments/reducer.js, src/payments/saga.js, src/payments/selectors.js, src/payments/service.js, src/reducers.js, src/sagas.js
ARCH-843
FYI: This is now ready for review.  It is a minimal payments page.
=>  ARCH-843: Initial temporary payments page

src/payments/service.js
Update to match https://github.com/edx/ecommerce/pull/2261
=> ARCH-752: update temporary baskets api endpoint

README.rst, package-lock.json, package.json, webpack/webpack.prod.config.js
LTR and RTL css files are now 41kb down from 251kb each.
=> feat: add purgecss to remove unused css from production build

.travis.yml, package-lock.json, package.json
- cleaning up .travis.yml
- bumping node-sass
=> node 12 and cleanup

src/components/App.jsx
=> fix: remove youtube logo from footer

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Added CODEOWNERS file to require @edx/revenue-squad review during merge-freeze
=> Added CODEOWNERS and announcement of merge-freeze

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Reverts edx/frontend-app-ecommerce#148
=> Revert "Added CODEOWNERS and announcement of merge-freeze"

.github/PULL_REQUEST_TEMPLATE.md, README.rst
Rephrased PR template advisory to be clear that all merges must be deployed; also added the message to README
Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.
Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, …
=> Rephrased PR template advisory to be clear that all merges must be deployed

src/order-history/service.js
https://2u-internal.atlassian.net/browse/REV-2817
The order history page isn't working properly in stage when set to get data via commerce-coordinator (via waffle flag). Add more logging to see what's available/where.
=> fix: add logging to troubleshoot stage issue

package-lock.json, package.json
Reverts openedx/frontend-app-ecommerce#199
This upgrade didn't get us to a better state for https://2u-internal.atlassian.net/browse/REV-2812
=> Revert "fix: Upgrade proptypes to v15.8.1"

.github/workflows/node-ci.yml
JIRA: https://2u-internal.atlassian.net/browse/BOM-3414
=> chore!: Dropped support for Node 12

src/order-history/service.js
Info gathering for stage issue [REV-2817.](https://2u-internal.atlassian.net/browse/REV-2817)  Add log line to confirm what's being used for orderFetchingUrl
Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.
Please provide detailed step-by-step instructions for testing …
=> fix: add new log line to confirm orderFetchingUrl

src/order-history/service.js
Now that order history is working in stage via commerce-coordinator ([REV-2817](https://2u-internal.atlassian.net/browse/REV-2817)), we no longer need the extra middle log lines. (Though I still have a couple in place for the prod verification during REV-2577). 
Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.
Useful information to include:
- Which edX user roles will this change impact? Common user roles …
=> Remove temporary log lines

package-lock.json, package.json, src/index.jsx
Major version upgrade of `@edx/paragon`.
This depends on the PR [220](https://github.com/openedx/frontend-app-ecommerce/pull/220) which is why the build is failing. Both PRs should be merged together.
=> build: major paragon version upgrade

package-lock.json, package.json
Fixed dependency issues by upgrading `@edx/frontend-component-header`
=> fix: upgraded frontend-component-header to fix dependency issues

.github/workflows/lockfileversion-check.yml, .github/workflows/node-ci.yml
[REV-3283](https://2u-internal.atlassian.net/browse/REV-3283)
=> build: add 2u/project-theseus branch to run ci

src/orders-and-subscriptions/OrdersAndSubscriptionsPage.jsx, src/orders-and-subscriptions/__snapshots__/OrdersAndSubscriptionsPage.test.jsx.snap
Revert maxwidth change to container
=> fix: revert change to container

src/orders-and-subscriptions/OrdersAndSubscriptionsPage.jsx, src/orders-and-subscriptions/selectors.js, src/store/__mocks__/mockEmptyStore.js, src/store/__mocks__/subscriptions.mockStore.js, src/subscriptions/actions.js, src/subscriptions/reducer.js, src/subscriptions/saga.js
Handle subscription section with api statusCode flag
[PON-299](https://2u-internal.atlassian.net/browse/PON-299)
=> feat: Handle subscription section with api statusCode flag

.github/workflows/node-ci.yml
Step 1 of https://github.com/openedx/frontend-app-ecommerce/issues/374
=> test: add node 20 to CI matrix
